spring:
  application:
    name: ecommerce-backend
  config:
    import: optional:classpath:application-local.yml
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        generate_statistics: true
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    from: no-reply@ecommerce.com
    username: ${SPRING_MAIL_USERNAME:test@localhost}
    password: ${SPRING_MAIL_PASSWORD:}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          timeout: 5000
          connection-timeout: 5000
          write-timeout: 5000


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false




server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.stat: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: vietprodev-secret-key-must-be-at-least-256-bits-long-for-hs256
  expiration-ms: 900000
  refresh-expiration-ms: 604800000

# Cấu hình Redis keys
redis:
  token:
    blacklist-prefix: "token:blacklist:"
    user-tokens-prefix: "user:tokens:"
    cleanup-cron: "0 0 * * * *"  # Mỗi giờ chạy 1 lần

vnpay:
  tmn-code: ${VNPAY_TMN_CODE:VSUMZHNG}
  hash-secret: ${VNPAY_HASH_SECRET:EHHY40NBTOOMQV68RX2X6HU0TEQXUVDB}
  payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8081/api/payment/vnpay-return